namespace MahalaxmiAPI.Models
{
    public class DispatchOrdersModel
    {
        public string DcpiNo { get; set; }
        public string SoldTo { get; set; }
        public string DcpiDt { get; set; }
        public string OrderNo { get; set; }
        public string OrderDt { get; set; }
        public string CustomerNameSoldTo { get; set; }
        public string DistributionChannel { get; set; }
        public string Division { get; set; }
        public string Spart { get; set; }
        public string Material { get; set; }
        public string MaterialDesc { get; set; }
        public decimal? Qty { get; set; }
        public string Uom { get; set; }
        public string Location { get; set; }
        public string SourceLocation { get; set; }
        public string PmtMethod { get; set; }
        public string PaymentMethodDesc { get; set; }
        public string PmtTerms { get; set; }
        public string LorryReceiptNo { get; set; }
        public string TruckNo { get; set; }
        public string TransportName { get; set; }
        public decimal? Tax { get; set; }
        public decimal? TotalAmt { get; set; }
        public string RetailInvoice { get; set; }
        public string Currency { get; set; }
        public string ShipTo { get; set; }
        public string CustomerNameShipTo { get; set; }
        public string ShipToCity { get; set; }
        public string Payer { get; set; }
        public string PayerName { get; set; }
        public string BatchNo { get; set; }
        public string GroupCompany { get; set; }
        public string GroupCompanyName { get; set; }
        public string ContractNo { get; set; }
        public string BoeNo { get; set; }
        public string SorDate { get; set; }
        public decimal? SorAmt { get; set; }
        public string PoNumber { get; set; }
        public string PoDate { get; set; }
        public string BillToNo { get; set; }
        public string CustomerNameBillTo { get; set; }
        public string QsplPmtMethod { get; set; }
        public string QsplPayMethodDesc { get; set; }
        public string ProductHsnCode { get; set; }
        public string BpGstNumber { get; set; }
        public decimal? CentralTax { get; set; }
        public decimal? StateTax { get; set; }
        public decimal? IntegratedTax { get; set; }
        public string GstInvoice { get; set; }
        public decimal? UnionTeritoryGst { get; set; }
        public string SalesOffice { get; set; }
        public string Sorgstno { get; set; }
        public string Taxinvoiceno { get; set; }
        public string Lcscrollno { get; set; }
        public string CustomerLcNo { get; set; }
        public string SourcePlant { get; set; }
        public string SourcePlantName { get; set; }
        public string BoeDate { get; set; }
        public string QsplInvoice { get; set; }
        public decimal? QsplAmt { get; set; }
        public string CustomDuty { get; set; }
        public decimal? CustomAmount { get; set; }
        public string EwayBillNumber { get; set; }
        public decimal? TcsAmount { get; set; }
        public decimal? TotalAmountPayable { get; set; }
        public decimal? TdsAmount { get; set; }
        public string QualityStatus { get; set; }
        public string Inco1 { get; set; }
        public string Inco2 { get; set; }
        public string Bezei { get; set; }
        public string CommercialInv { get; set; }
        public string CommercialCurr { get; set; }
        public decimal? CommercialValue { get; set; }
        public string Vkorg { get; set; }
        public string Bukrs { get; set; }
        public decimal? BasicAmount { get; set; }
        public decimal? BasicAmountWoTds { get; set; }
    }
}